services:
  postgres:
    image: postgres:16-alpine
    container_name: projects-menagment-postgres
    environment:
      POSTGRES_DB: projects_menagment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d projects_menagment"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    container_name: projects-menagment-api
    build:
      context: .
      dockerfile: src/projects-menagment.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=projects_menagment;Username=postgres;Password=postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  postgres_data:
